### PR TITLE
Do not overwrite existing output file: instead error

### PR DESCRIPTION
**Pull request by Craig-Macomber**
I think overwriting an existing file is a bad idea for such an application (someone might accidentally overwrite a key without noticing: this can be very bad even if they have a backup, since they then use the new key without backing it up). This change returns an error instead of silently overwriting a file.
Example errors:
Error generating key pair: open /home/craig/decred/testkey: file exists
Error generating seed: open /home/craig/decred/testkey: file exists

### CODE REVIEW

**Comment by cjepson** [comment]
Looks good, just a couple stylistic changes I'd prefer then I'll ACK it.

**Comment by Craig-Macomber** [comment]
I think that new commit addresses your requests. It's a bit fussy since we want to close in two different cases (the error case and the normal case). Updated version still does this, but now matching your style (instead of the standard library style: https://golang.org/src/io/ioutil/ioutil.go?s=2520:2588#L66 ). I think your style is more readable in this case anyway. Thanks for the quick response!

**Comment by cjepson** [comment]
No problem. Yeah, I see the issue now. I'm not sure if the second error (for close) really needs to be caught if there is an issue writing, although the original code is not ideal and also throws away the Close error. I hate returning the final err in this way because of clarity reasons. Often the btcsuite code tries to make the branch execution more clear by avoiding ending functions with return err/return func.

ntACK, squash and rebase and then I'll wait for an ACK from jcv and we can merge. Thank you!

**Comment by jcvernaleo** [comment]
Looks good to me.  Just squash it to one commit and it is all good to go in for me.

**Comment by Craig-Macomber** [comment]
Ok. Squashed to one commit.

**Comment by jcvernaleo** [comment]
It is in.  Thanks @Craig-Macomber !

**Pull request merged**
